---
title: "Final-Prioritization"
author: "Bri Baker"
date: "11/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(sf)
library(tidyverse)
library(tmap)
```

## REQUIRED DATA

All required data layers are in this github repo

```{r}
##Read in layers
#restoration success, classified 1-5, NAD83 / California Albers
resto <- st_read(
  here("shapefiles_written", "resto_classed.shp"))

#wildfire risk, classified 1-5, NAD83 / California Albers
fire <- st_read(
  here("shapefiles_written", "WHP_fire_risk.shp"))

#Biodiversity score, classified 1-5, NAD83 / California Albers
biodiv <- st_read(
  here("shapefiles_written", "conservation_classed.shp"))
```

```{r}
## Filter biodiv to riparian forest

biodiv <- biodiv %>% 
  filter(calvgnm %in% c("Black Cottonwood", 
                         "Black Walnut", 
                         "California Sycamore", 
                         "Coast Live Oak", 
                         "Fremont Cottonwood", 
                         "Riparian Mixed Hardwood",
                         "Willow (tree)"),
         arnd_cv != 0)

```



```{r}
##Combine layer info into one priority layer

resto <- resto %>% 
  select(acres:rst_scc)

biodiv <- biodiv %>% 
  select(layer:cnsrvt_)

priority <- cbind(resto, fire)
  
priority <- cbind(priority, biodiv)

```


```{r}
## do MCA

priority <- priority %>% 
  mutate(
    resto_priority = rst_scc + WHP_cls + cnsrvt_
  )


```



```{r}
## Write shapefile

#st_write(priority, here("shapefiles_written", "restoration_priority_whp.shp"))

```

```{r}
# top sites summary

priority_summary <- priority %>% 
  select(rst_scc,
         WHP_cls,
         cnsrvt_,
         resto_priority) %>% 
  filter(rst_scc %in% c(4,5)) # filter top resto success

fire_resto <- priority_summary %>% 
  filter(WHP_cls %in% c(4,5))

bio_resto <- priority_summary %>% 
  filter(cnsrvt_ %in% c(4,5))

both_resto <- fire_resto %>% 
  filter(cnsrvt_ %in% c(4,5))

# Save as shapefiles

st_write(fire_resto, here("shapefiles_written", "fire_resto.shp"))

st_write(bio_resto, here("shapefiles_written", "bio_resto.shp"))

st_write(both_resto, here("shapefiles_written", "both_resto.shp"))

```


