---
title: "fire_risk_for_real"
author: "Iris Foxfoot"
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(sp)
library(sf)
library(raster)
library(fasterize)
```

```{r}
#read in veg layer for lower Santa Clara Watershed
bios_veg_layer <- st_read(here("bios_veg_layer", "ds983.gdb")) %>% 
  filter(!st_is_empty(.)) %>% 
  clean_names() %>% 
  st_buffer(dist = 0)

#add ID column
bios_veg_layer <- tibble::rowid_to_column(bios_veg_layer, "ID")

#plot data to view data
options(sf_max.plot = 1)
plot(bios_veg_layer)
```

```{r}
#create a raster covering the same area that the bios veg layer covers
blank_raster <- raster(ncol=5366, nrow=2992, xmn=67134.41, xmx=120794.4, ymn=-423477, ymx=-393557)

#set resolution
res(blank_raster) <- 10

#set crs to match bios veg layer
crs(blank_raster) <- "+proj=aea +lat_0=0 +lon_0=-120 +lat_1=34 +lat_2=40.5 +x_0=0 +y_0=-4000000 +datum=NAD83 +units=m +no_defs"

#call it to view information
blank_raster
```

```{r}
#At a later date....determine if there are more flammable things to include

#create new dataframe that has a column where flammable veg is coded as one, all else zero
bios_veg_layer_flammable <- bios_veg_layer %>% 
  mutate(flammable = case_when(calvegname %in% c("Non-Native/Invasive Forb/Grass", "Perennial Grasses and Forbs", "Basin Sagebrush", "California Sagebrush", "Soft Scrub-Mixed Chaparral", "Annual Grasses and Forbs") ~ 1, T ~ 0))

#rasterize the polygon, using flammable category as the raster value
bios_veg_layer_raster <- fasterize(bios_veg_layer_flammable, blank_raster, "flammable")

#plot it to view
plot(bios_veg_layer_raster)
```

```{r}
#filter bios veg layer for polygons containing trees...aka forests
bios_veg_layer_forest <- bios_veg_layer %>% 
  filter(calvegname %in% c("Black Cottonwood", "Black Walnut", "California Sycamore", "Coast Live Oak", "Fremont Cottonwood", "Riparian Mixed Hardwood", "Willow (tree)")) %>% 
  filter(arundo_cov!=0)

#plot filtered forest polygons to view data
options(sf_max.plot = 1)
plot(bios_veg_layer_forest)
```

```{r}
#buffer forest polygons to 10 m
bios_veg_layer_buffered <- bios_veg_layer_forest %>% 
  st_buffer(dist = 10)

#plot buffered polygons
options(sf_max.plot=1)
plot(bios_veg_layer_buffered)
```

```{r}
#extract flammable values for each polygon (unbuffered)
# extract_flammable_unbuffered <- raster::extract(bios_veg_layer_raster, bios_veg_layer_forest, fun=mean, na.rm = T, df = T)
#check to make sure values are zero

#extract flammable values for each polygon (buffered)
extract_flammable_buffered <- raster::extract(bios_veg_layer_raster, bios_veg_layer_buffered, fun=mean, na.rm = T, sp =T)

#convert to sf
extract_flammable_buffered_sf <- st_as_sf(extract_flammable_buffered)
```

```{r}
library(tmap)

#make map ranking them
tmap_mode("view")

tm_basemap("Esri.WorldTopoMap") +
tm_shape(extract_flammable_buffered_sf) +
  tm_fill("layer", title = "Fire Risk", palette = "Spectral") +
  tm_view(set.view = 12)
```

```{r}
#class
fire_risk_classed <- extract_flammable_buffered_sf %>% 
  mutate(fire_risk = ntile(layer, 5))
```

```{r}
fire_risk_classed_df <- as_data_frame(fire_risk_classed) %>% 
  dplyr::select("fire_risk", "ID")

fire_risk_forest_polygon <- merge(fire_risk_classed_df, bios_veg_layer_forest, by = "ID")
```

```{r}
st_write(fire_risk_forest_polygon, here("shapefiles_written", "fire_risk.shp"))
```


